### ISSUE TITLE
Clickable external link in desktop view doesn't work

### ISSUE THREAD

**Issue by wewlad-dev** [Kielx/terminal-portfolio#22]
Adding an external site or subdomain in the slug will not open that link in the desktop view once clicked, and still open the terminal winbox window. However, in the mobile view, it does open and work as expected.
I believe because once it checks for mobile resolution, it does this

`const infoMobile = data.info.edges.map(item => (
    <li key={item.node.frontmatter.title} className="infoItem">
      <Link
        className="popupWindowLinkButton"
        style={{ cursor: "pointer" }}
        to={item.node.frontmatter.slug}
      >
        {item.node.frontmatter.listName}
      </Link>
    </li>
  ))`

Where the slug becoming the link.
How to have some of the pages clickable to external sites in the desktop view as if it's in the mobile one, while also the rest of the pages remain with the current setup (opening in the winbox window)?

**Comment by Kielx** [comment]
Hello @wewlad-dev - thanks for creating an issue.
 
While designing the Terminal Portfolio I wanted to create new windows with descriptions for projects based on markdown files keeping the external links as clickable icon-buttons that are located below project images. Therefore I haven't had the need to direct users to external sites while clicking projects because I thought that this could be confusing and bad for the user experience. 

If you would like to organize it that way while still maintaining the rest of the setup you just need to update the onClick function of items rendered as projects in itemsList.js 
Inside that function, you should then check the frontmatter of the project markdown file for the existence of externalLink variable which would work as a flag, that when truthy causes the clickable link to direct the user to your link provided in slug frontmatter. 
I have created a [new branch](https://github.com/Kielx/terminal-portfolio/tree/22-clickable-external-link-in-desktop-view-doesnt-work) based on your issue. See the [changes](https://github.com/Kielx/terminal-portfolio/commit/43ea0e43215641aa89419502748ff08aefd48e1b) inside of it and try to click on Arduino-Knight-Rider project. It should redirect you to an external site as you wanted. You can then use this technique to fit your needs.

I hope that resolves your issue 👍

**Comment by wewlad-dev** [comment]
Thanks @Kielx ! That did the trick, I also modified the "info" section too to have the same condition, not just the projects!
Awesome terminal portfolio too, can't say I know a lot of Gatsby but been playing around with it and learning in the process too, thanks again!
